apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: my-issuer
spec:
  tls:
  - hosts:
      - argo.aws-project.click
    secretName: argo-aws-project-click-tls
  rules:
  - host: argo.aws-project.click
    http:
      paths:
        - path: /
          pathType: Prefix

          backend:
            service:
              name: argocd-server
              port:
                number: 80
